TARGET = build_in.o
#COMOBJS = ../common/proto.o   #公共模块
CC = g++
LD = ld
CCFLAGS += -c 

SRCS = $(wildcard *.cpp)
OBJS = $(patsubst %.cpp,%.o,$(SRCS))  #子目录obj

$(TARGET) : $(OBJS) $(COMOBJS)
	$(LD) -r $^ -o $@ $(LIBS) $(LDFLAGS) 
%.o : %.cpp
	$(CC) $< -o $@ $(CCFLAGS) $(INCLUDES)
.PHONY:clean
clean:
	rm -rf *.o
	rm -rf $(TARGET) 
	rm -rf Makefile

