#ifndef __VALUE_TYPE_H__
#define __VALUE_TYPE_H__

enum value_type_e{
	VALUE_TYPE_UNDEFINED = 0, 
	VALUE_TYPE_INT8_T,
	VALUE_TYPE_UINT8_T,
	VALUE_TYPE_INT16_T,
	VALUE_TYPE_UINT16_T,
	VALUE_TYPE_INT32_T,
	VALUE_TYPE_UINT32_T,
	VALUE_TYPE_INT64_T,
	VALUE_TYPE_UINT64_T,
	VALUE_TYPE_FLOAT_T,
	VALUE_TYPE_ALLOC_POINTER,
	VALUE_TYPE_STRUCT_POINTER,
	VALUE_TYPE_STUB_POINTER,
	VALUE_TYPE_OBJ_POINTER,
	VALUE_TYPE_STRING_POINTER,   /*todo:这个可以和VALUE_TYPE_OBJ_POINTER合并*/
	VALUE_TYPE_CSTRING_POINTER,  /*todo:等VALUE_TYPE_STRING_POINTER和这个可以和VALUE_TYPE_OBJ_POINTER合并后, 改名为VALUE_TYPE_STRING_POINTER*/
	VALUE_TYPE_MAX_TYPE,
};

#endif
