FROM ubuntu:20.04

ARG TAR_PACKAGE_PATH
ENV TAR_PACKAGE_PATH ${TAR_PACKAGE_PATH}

RUN echo "deb http://mirrors.huaweicloud.com/ubuntu/ focal main restricted universe multiverse" > /etc/apt/sources.list              && \
    echo "deb http://mirrors.huaweicloud.com/ubuntu/ focal-updates main restricted universe multiverse" >> /etc/apt/sources.list     && \
    echo "deb http://mirrors.huaweicloud.com/ubuntu/ focal-backports main restricted universe multiverse" >> /etc/apt/sources.list   && \
    echo "deb http://mirrors.huaweicloud.com/ubuntu/ focal-security main restricted universe multiverse" >> /etc/apt/sources.list

RUN  apt-get update

RUN  apt-get install -y net-tools && apt-get install -y iputils-ping && apt-get install -y libmysqlclient-dev

RUN mkdir -p /root/softs
COPY ${TAR_PACKAGE_PATH} /root/softs/

RUN export TAR_NAME=$(basename ${TAR_PACKAGE_PATH}) \
    && echo "处理文件: ${TAR_NAME}" \
    && mkdir -p /root/.xtools/sysroot \
    && tar -xzf /root/softs/${TAR_NAME} -C /root/.xtools/sysroot --strip-components 1

RUN mkdir -p /root/.xtools/node
COPY ./doc/node/node.json /root/.xtools/node

WORKDIR /root/.xtools/sysroot/bin
CMD export LD_LIBRARY_PATH=/root/.xtools/sysroot/lib:/root/.xtools/sysroot/lib64:$LD_LIBRARY_PATH                                             && \ 
    ldconfig && ./xtools node --log-level=0x30016 --host=0.0.0.0 --service=12345 --deamon=t >/root/.xtools/node/logs
# CMD ["tail", "-f", "/dev/null"]