#ifndef __HTTP_STATUS_H__
#define __HTTP_STATUS_H__

enum http_status_e {
    STATUS_INIT = 1,
    STATUS_READ_START_LINE,
    STATUS_READ_HEADERS,
    STATUS_READ_BODY,
    STATUS_PARSE_START_LINE,
    STATUS_PARSE_HEADERS,
    STATUS_PARSE_BODY,
    STATUS_PROCESS_START_LINE,
    STATUS_PROCESS_HEADERS,
    STATUS_PROCESS_BODY,
};

#endif
