#!/usr/bin/env bash
OPTION_HELP="false"
OPTION_PLATFORM=""
OPTION_INSTALL="false"
OPTION_BUILD="false"
OPTION_DB_IP=""
OPTION_TO_PATH="~/.xtools/packages"
OPTION_PACKAGE_PATH=""
OPTION_NAME=""
OPTION_ARGS=""
OPTION_REMOVE="false"
OPTION_RUN="false"
OPTION_IP=""
CMD_BUILD="false"
CMD_NAME="false"
expect_command_prefix=